name: MedBox
description: A product by saint spluussh.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  build_runner: ^2.3.3
  camera: ^0.10.4
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  date_picker_timeline: null
  file_picker: ^5.2.5
  firebase_app_check: ^0.1.1+12
  cached_network_image: ^3.2.3
  firebase_auth: null
  firebase_core: ^2.4.1
  firebase_messaging: ^14.6.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^2.0.0
  flutter_timezone: ^1.0.6
  gallery_saver: null
  google_sign_in: ^5.4.4
  http: ^0.13.5
  image_picker: ^0.8.6+3
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  localization: ^2.1.0
  lottie: any
  path_provider: ^2.0.14
  permission_handler: ^10.3.0
  provider: ^6.0.5
  riverpod_annotation: ^2.1.1
  share_plus: any
  shared_preferences: ^2.0.17
  shimmer: ^3.0.0
  sleek_circular_slider: null
  sqflite: ^2.2.4+1
  syncfusion_flutter_charts: ^21.1.41
  url_launcher: ^6.1.10
  velocity_x: null
  flutter_cache_manager: ^3.3.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.2.3
  riverpod_lint: 1.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - lib/l10n/

  fonts:
    - family: Pop
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
