name: MedBox
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  date_picker_timeline: null
  file_picker: ^5.2.5
  firebase_app_check: ^0.1.1+12
  firebase_auth: null
  firebase_core: ^2.4.1
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  google_sign_in: ^5.4.4
  http: ^0.13.5
  image_picker: ^0.8.6+3
  intl: any
  lottie: any
  path_provider: ^2.0.14
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  showcaseview: ^2.0.2
  sqflite: ^2.2.4+1
  velocity_x: ^3.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Pop
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Popb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Wastinger
      fonts:
        - asset: assets/fonts/WastingerDisplayFreePersonal-MVydr.ttf
